# Generated by Django 3.1.7 on 2021-04-05 12:21

import Audio.models
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration_in_sec', models.PositiveIntegerField()),
                ('uploaded_time', models.DateField(default='2021-04-05', validators=[Audio.models.validate_date])),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_in_sec', models.PositiveIntegerField()),
                ('uploaded_time', models.DateField(default='2021-04-05', validators=[Audio.models.validate_date])),
                ('host', models.CharField(max_length=100)),
                ('participants', django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=1010, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_in_sec', models.PositiveIntegerField()),
                ('uploaded_time', models.DateField(default='2021-04-05', validators=[Audio.models.validate_date])),
            ],
        ),
    ]
